# Generated by Django 5.0.3 on 2024-09-19 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
